# Generated by Django 4.2.7 on 2023-11-10 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pres_code', models.CharField(max_length=10, null=True)),
                ('patient_name', models.CharField(max_length=255, null=True)),
                ('patient_phone', models.CharField(max_length=255, null=True)),
                ('hosp_name', models.CharField(max_length=255, null=True)),
                ('pdate', models.DateField()),
                ('prescriber_name', models.CharField(max_length=255, null=True)),
                ('prescriber_qualification', models.CharField(max_length=255, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_brand', models.BooleanField(default=False)),
                ('brand_name', models.CharField(max_length=255, null=True)),
                ('generic_name', models.CharField(max_length=255, null=True)),
                ('sig', models.TextField()),
                ('status', models.CharField(max_length=255, null=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescribe.prescribe')),
            ],
        ),
    ]
