# Generated by Django 4.2.6 on 2023-11-01 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lookups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Custname', models.CharField(max_length=255, null=True)),
                ('TinNum', models.CharField(max_length=255, null=True)),
                ('PhoneNum', models.CharField(max_length=255, null=True)),
                ('Addr', models.CharField(max_length=255, null=True)),
                ('ZoneID', models.IntegerField(null=True)),
                ('Inserted_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('latitude', models.IntegerField(null=True)),
                ('longitude', models.IntegerField(null=True)),
                ('isApproved', models.BooleanField(blank=True, default=False, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bentity_approve', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_in_area', to='area.area')),
                ('compType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bentity', to='Lookups.entitytype')),
                ('customerClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bentity', to='Lookups.customerclass')),
                ('insertedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bentity_insert', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Profession', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lookups.jobposition')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactperson', to='entity.entity')),
            ],
        ),
    ]
