# Generated by Django 4.2.6 on 2023-11-01 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phones', models.CharField(blank=True, max_length=255, null=True)),
                ('latt', models.FloatField()),
                ('longt', models.FloatField()),
                ('tin', models.CharField(max_length=15)),
                ('isApproved', models.BooleanField(blank=True, default=False, null=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('areaid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitals_in_area', to='area.area')),
            ],
        ),
    ]
