# Generated by Django 4.2.6 on 2023-11-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=255, null=True)),
                ('specialization', models.CharField(max_length=25, null=True)),
                ('phoneNumber', models.CharField(max_length=255, null=True)),
                ('dob', models.DateField(auto_now_add=True, null=True)),
                ('hobby', models.CharField(max_length=25, null=True)),
                ('region', models.CharField(max_length=25, null=True)),
                ('orientation', models.CharField(max_length=25, null=True)),
                ('customerClass', models.CharField(max_length=25, null=True)),
                ('isClinicOwner', models.BooleanField(blank=True, default=False, null=True)),
                ('hosp', models.ManyToManyField(related_name='doctors', to='hospital.hospital')),
            ],
        ),
    ]
